// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


// get all the fib terms till 4000000. 
// extract even
// sum of even

sumOfEvenFibNumbers(4000000);

function sumOfEvenFibNumbers(limit) {
    let fibNumbers = [1, 2];
    let startIndex = 2;
    let nextFibNumber = 0;
    let sumOfEvenFibNumbers = 0;

    while(true) {
        nextFibNumber = fibNumbers[startIndex - 2] + fibNumbers[startIndex - 1];
        if(nextFibNumber<=limit){
            fibNumbers.push(nextFibNumber);
            if(nextFibNumber%2 == 0){
                sumOfEvenFibNumbers = sumOfEvenFibNumbers + nextFibNumber;
            }
            startIndex++;
        } else {
            break;
        }
    }; 
    console.log("Sum of even Fib numbers till " + limit + ": " + sumOfEvenFibNumbers);
}